### ISSUE TITLE
SignatureDoesNotMatch for chunked uploads

### ISSUE THREAD

**Issue by rnicholus** [stratospark/zappa-s3-signature#1]
Looks like there may be an issue with the signature logic on your Lambda. Files smaller than 5 MiB are sent in a single request, non-chunked, with a policy file using the S3 HTML form upload endpoint. Files larger than 5 MiB are chunked by Fine Uploader and sent through the AWS Multipart Upload Rest API. You already know this, but I wanted to be complete in my explanation.

The non-chunked signatures are working flawlessly, but there appears to be an issue with larger/chunked files. Most likely some error in the signing logic inside the [`sign_headers` function](https://github.com/stratospark/zappa-s3-signature/blob/master/my_app.py#L47).

**Comment by stratospark** [comment]
Ah I ran into this before, but the problem went away when I switched to the default AWS region. I believe that if you are using a different region, the signature is wrong. I switched to us-west-1 for the live demo at the last moment. 

If I recall, there should only be one "/" in front of the file name. Let me see if I can debug this locally. I usually just run `python my_app.py` to start up a local server then point Fine Uploader to localhost:5000

![image](https://cloud.githubusercontent.com/assets/93366/23053871/2acce384-f491-11e6-8259-ee460f7a93b4.png)

**Comment by stratospark** [comment]
Never mind! It was something entirely else. I just had to remove the trailing slash from the request/endpoint url. Fixed in the client: https://github.com/stratospark/react-fineuploader-s3-demo/commit/c5f62c7380b96e8c36725d8c1483a42867457207

Thanks for catching this and all your work on Fine uploader!

**Comment by rnicholus** [comment]
Confirmed as fixed. Let me know if there is anything I can do to help with this or anything else. Looking forward to part 2 of your article.
